

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: root
    password: 123



  liquibase:
    change-log: classpath:liquibase/changelog.yml


  garage:
    size: 2
server:
  port: 8080
